host_model: 
  hf_name: "meta-llama/Llama-3.2-1B"
  layer_start: 10
  layer_end: 15

optim:
  num_epochs: 1000
  learning_rate: 1e-3
  weight_decay: 1e-4
  batch_size: 256
  type: "adamw"

wandb: 
  use_wandb: False
  entity: "nishantaswani"
  project: "koopman_interp"

autoencoder:
  k_steps: 1
  in_features: 2048
  hidden_config: [1024]
  ae_dim: 512
  ae_nonlinearity: "leaky_relu"
  bias: True
  batchnorm: True
  lambda_reconstruction: 1e0
  lambda_state_pred: 1e0
  lambda_obs_pred: 1e0
  koopman_param: "exponential"

verbose: True
seed: 22
print_freq: 20
save_name: "dummy"
