host_model: 
  hf_name: "google/vit-base-patch16-224"
  layer_start: 5
  layer_end: 10

optim:
  num_epochs: 1000
  learning_rate: 1e-3
  weight_decay: 1e-4
  batch_size: 256
  type: "adamw"

wandb: 
  use_wandb: False
  entity: "nishantaswani"
  project: "new_koopmann"

autoencoder:
  k_steps: 1
  in_features: 768
  hidden_config: [1024]
  ae_dim: 1024
  ae_nonlinearity: "leaky_relu"
  bias: True
  batchnorm: True
  lambda_reconstruction: 1e-1
  lambda_state_pred: 1e-1
  lambda_obs_pred: 1e-1
  koopman_param: "exponential"

verbose: True
seed: 22
print_freq: 20
save_name: "dummy"
