model: 
    out_features: 10
    hidden_neurons: [128, 64, 32, 16]

optim: 
    weight_decay: 1e-2
    num_epochs: 30
    learning_rate: 1e-2

train_data: 
    dataset_name: "MNISTDataset"
    num_samples: 60_000
    split: "train"
    torch_transform: null
    seed: 42
    negative_label: false

wandb: 
    use_wandb: true
    entity: "nishantaswani"
    project: "koopman_interp"

seed: 0
batch_size: 4_096
print_freq: 5
task_type: "classifier"
save_name: "mnist_model"
save_dir: "/scratch/nsa325/koopmann_model_saves/"