name: train_sweep
method: grid
metric:
  name: train_loss
  goal: minimize

wandb: 
  use_wandb: True
  entity: "nishantaswani"
  project: "koopman_interp"

model: 
  parameters:
      residual: True
      out_features: 10
      hidden_neurons: [512,512,512,512,512,512,512,512]

optim: 
    parameters:
      type: "adamw"
      weight_decay: 1e-2
      num_epochs: 200
      learning_rate: 1e-1

train_data: 
  parameters:
      dataset_name: "MNISTDataset"
      num_samples: 60_000
      split: "train"
      torch_transform: null
      seed: 42
      negative_label: False

seed: 0
batch_size: 1_024
print_freq: 5
task_type: "classifier"
save_name: "mnist_model"
save_dir: "/scratch/nsa325/koopmann_model_saves/"

parameters:
  learning_rate:
    values: [0.1, 0.001]