model: 
    conv: False
    residual: True
    hidden_neurons: [10, 10, 10, 10, 10, 10, 10, 10]
    bias: True
    batchnorm: True

optim: 
    type: "sgd"
    weight_decay: 5e-4
    num_epochs: 2_000
    learning_rate: 1e-2

train_data: 
    dataset_name: "YinYangDataset"
    num_samples: 5_000
    split: "train"
    torch_transform: null
    seed: 42
    negative_label: False

wandb: 
    use_wandb: True
    entity: "nishantaswani"
    project: "koopman_interp"

adv: 
    use_adversarial_training: False
    epsilon: 0.08

seed: 0
batch_size: 512
print_freq: 100
task_type: "classifier"
save_dir: "/Users/nsa325/koopmann_model_saves/"
suffix: "yinyang"



