model: 
    conv: True
    bias: False
    batchnorm: True

optim: 
    type: "sgd"
    weight_decay: 5e-4
    num_epochs: 30
    learning_rate: 1e-1

train_data: 
    dataset_name: "CIFAR10Dataset"
    num_samples: 50_000
    split: "train"
    torch_transform: null
    seed: 42
    negative_label: False

wandb: 
    use_wandb: True
    entity: "nishantaswani"
    project: "koopman_interp"

adv: 
    use_adversarial_training: True
    epsilon: 0.08

seed: 0
batch_size: 128
print_freq: 5
task_type: "classifier"
save_dir: "/scratch/nsa325/koopmann_model_saves/"
suffix: "cifar10"