train_data: 
  dataset_name: "MNISTDataset"
  num_samples: 60_000
  split: "train"
  torch_transform: null
  seed: 42
  negative_label: false

optim:
  num_epochs: 500
  learning_rate: 1e-3
  weight_decay: 1e-4
  type: "adamw"

scale:
  model_to_scale: "/scratch/nsa325/koopmann_model_saves/resmlp.safetensors"
  scale_location: 0
  num_scaled_layers: 1

wandb: 
    use_wandb: true
    entity: "nishantaswani"
    project: "koopman_interp"

autoencoder:
  ae_dim: 2048
  hidden_config: []
  ae_nonlinearity: "leaky_relu"
  batchnorm: False
  lambda_reconstruction: 1
  lambda_state_pred: 1e-1
  lambda_latent_pred: 1e-1
  lambda_isometric: 0
  koopman_param: "lowrank"
  koopman_rank: 20

task_type: "autoencoder"
batch_size: 16_384
seed: 21
save_name: "mnist_model"
save_dir: "/scratch/nsa325/koopmann_model_saves/"
print_freq: 5
