train_data: 
  dataset_name: "FashionMNISTDataset"
  num_samples: 60_000
  split: "train"
  torch_transform: null
  seed: 42
  negative_label: false

optim:
  num_epochs: 200
  learning_rate: 5e-4
  weight_decay: 1e-2
  betas: [0.9, 0.999]

scale:
  model_to_scale: "/scratch/nsa325/koopmann_model_saves/fashion_model.safetensors"
  model_with_probe: "/scratch/nsa325/koopmann_model_saves/fashion_probed.safetensors"
  scale_location: 0
  num_scaled_layers: 1

wandb: 
    use_wandb: true
    entity: "nishantaswani"
    project: "koopman_interp"

autoencoder:
  ae_dim: 1_024
  hidden_config: []
  ae_nonlinearity: "leaky_relu"
  batchnorm: False
  lambda_reconstruction: 1
  lambda_prediction: 0.05
  lambda_id: 1
  koopman_param: "lowrank"
  koopman_rank: 50
  
batch_size: 2_048
seed: 21
task_type: "autoencoder"
save_name: "fashion_model"
save_dir: "/scratch/nsa325/koopmann_model_saves/scaling/"
print_freq: 5
