train_data: 
  dataset_name: "CIFAR10Dataset"
  num_samples: 50_000
  split: "train"
  torch_transform: null
  seed: 42
  negative_label: False

optim:
  num_epochs: 200
  learning_rate: 5e-3
  weight_decay: 5e-2
  type: "adamw"

scale:
  model_to_scale: "/scratch/nsa325/koopmann_model_saves/convresnet_cifar10.safetensors"
  scale_location: 1
  num_scaled_layers: 10

wandb: 
    use_wandb: True
    entity: "nishantaswani"
    project: "koopman_interp"

autoencoder:
  preprocess: True
  pca_dim: 2_000
  ae_dim: 1_000
  hidden_config: [1_500, 1_000]
  ae_nonlinearity: "leaky_relu"
  batchnorm: False
  lambda_reconstruction: 1e0
  lambda_state_pred: 1e0
  lambda_latent_pred: 1e0
  lambda_isometric: 1e-3
  koopman_param: "exponential"
  whiten_alpha: 1

adv: 
    use_adversarial_training: False
    epsilon: 0.08

task_type: "autoencoder"
batch_size: 1_024
seed: 21
save_name: "cifar10_model"
save_dir: "/scratch/nsa325/koopmann_model_saves/"
print_freq: 5
