train_data: 
  dataset_name: "TorusDataset"
  num_samples: 5_000
  split: "train"
  torch_transform: null
  seed: 42
  negative_label: False

optim:
  num_epochs: 500
  learning_rate: 1e-1
  weight_decay: 5e-4
  type: "adamw"

scale:
  model_to_scale: "/Users/nsa325/koopmann_model_saves/resmlp_torus.safetensors"
  scale_location: 1
  num_scaled_layers: 100

wandb: 
    use_wandb: True
    entity: "nishantaswani"
    project: "koopman_interp"

autoencoder:
  preprocess: True
  pca_dim: 10
  ae_dim: 3
  hidden_config: [30]
  ae_nonlinearity: "leaky_relu"
  batchnorm: False
  lambda_reconstruction: 1e0
  lambda_state_pred: 1e0
  lambda_latent_pred: 1e0
  lambda_isometric: 0
  koopman_param: "exponential"
  # koopman_rank: 20
  whiten_alpha: 1

adv: 
    use_adversarial_training: False
    epsilon: 0.08

task_type: "autoencoder"
batch_size: 256
seed: 21
save_name: "torus_model"
save_dir: "/Users/nsa325/koopmann_model_saves/"
print_freq: 10