train_data: 
  dataset_name: "LotusRootDataset"
  num_samples: 3_000
  split: "train"
  torch_transform: null
  seed: 42
  negative_label: false

optim:
  num_epochs: 5_000
  learning_rate: 8e-3
  weight_decay: 1e-4
  betas: [0.9, 0.999]

scale:
  model_to_scale: "/home/nsa325/work/koopmann/model_saves/lotusroot_model.safetensors"
  scale_location: 1
  num_scaled_layers: 100

autoencoder:
  ae_dim: 20
  lambda_reconstruction: 5
  lambda_prediction: 1
  lambda_id: 1
  ae_nonlinearity: "leaky_relu"

batch_size: 5_000
seed: 21
save_name: "lotusroot_model"
save_dir: "/home/nsa325/work/koopmann/model_saves/scaling/"
print_freq: 500
