train_data: 
  dataset_name: "LotusRootDataset"
  num_samples: 3_000
  split: "train"
  torch_transform: null
  seed: 42
  negative_label: false

optim:
  num_epochs: 5_000
  learning_rate: 1e-2
  weight_decay: 1e-2
  type: "adamw"

scale:
  model_to_scale: "/scratch/nsa325/koopmann_model_saves/resmlp.safetensors"
  scale_location: 1
  num_scaled_layers: 1

wandb: 
    use_wandb: true
    entity: "nishantaswani"
    project: "koopman_interp"

autoencoder:
  ae_dim: 20
  hidden_config: [40]
  ae_nonlinearity: "leaky_relu"
  batchnorm: False
  lambda_reconstruction: 1
  lambda_prediction: 1e-3
  lambda_id: 1
  koopman_param: "lowrank"
  koopman_rank: 10

task_type: "autoencoder"
batch_size: 1_000
seed: 21
save_name: "lotusroot_model"
save_dir: "/scratch/nsa325/koopmann_model_saves/"
print_freq: 500
