train_data: 
  dataset_name: "MNISTDataset"
  num_samples: 60_000
  split: "train"
  torch_transform: null
  seed: 42
  negative_label: false

optim:
  num_epochs: 200
  learning_rate: 2e-3
  weight_decay: 1e-2
  betas: [0.9, 0.999]

scale:
  model_to_scale: "/scratch/nsa325/koopmann_model_saves/mnist_model.safetensors"
  model_with_probe: "/scratch/nsa325/koopmann_model_saves/mnist_probed.safetensors"
  scale_location: 0
  num_scaled_layers: 1

wandb: 
    use_wandb: true
    entity: "nishantaswani"
    project: "koopman_interp"

autoencoder:
  ae_dim: 1_024
  hidden_config: []
  ae_nonlinearity: "leakyrelu"
  batchnorm: False
  exp_param: False
  lambda_reconstruction: 1
  lambda_prediction: 1e-1
  lambda_id: 1e-5
batch_size: 4_096
seed: 21
task_type: "autoencoder"
save_name: "mnist_model"
save_dir: "/scratch/nsa325/koopmann_model_saves/scaling/"
print_freq: 5
