probe: 
    model_to_probe: "/scratch/nsa325/koopmann_model_saves/mnist_model_residual.safetensors"

optim: 
    type: "adamw"
    weight_decay: 1e-1
    num_epochs: 100
    learning_rate: 1e-3

train_data: 
    dataset_name: "MNISTDataset"
    num_samples: 60_000
    split: "train"
    torch_transform: null
    seed: 42
    negative_label: false

wandb: 
    use_wandb: true
    entity: "nishantaswani"
    project: "koopman_interp"

seed: 0
batch_size: 256
print_freq: 1
save_name: "mnist_probed"
save_dir: "/scratch/nsa325/koopmann_model_saves/"
task_type: "probe"