train_data: 
  dataset_name: "YinYangDataset"
  num_samples: 3_000
  split: "train"
  torch_transform: null
  seed: 42
  negative_label: false

optim:
  num_epochs: 5_000
  learning_rate: 3e-3
  weight_decay: 1e-4
  betas: [0.9, 0.999]

scale:
  model_to_scale: "/home/nsa325/work/koopmann/model_saves/yinyang_model.safetensors"
  scale_location: 1
  num_scaled_layers: 100

autoencoder:
  ae_dim: 30
  lambda_reconstruction: 3
  lambda_prediction: 1
  ae_nonlinearity: "leakyrelu"

batch_size: 1_000
seed: 21
save_name: "yinyang_model"
save_dir: "/home/nsa325/work/koopmann/model_saves/scaling/"
print_freq: 500
