train_data: 
  dataset_name: "MNISTDataset"
  num_samples: 60_000
  split: "train"
  torch_transform: null
  seed: 42
  negative_label: false

optim:
  num_epochs: 200
  learning_rate: 3e-4
  weight_decay: 1e-4
  betas: [0.9, 0.999]

scale:
  model_to_scale: "/home/nsa325/work/koopmann/model_saves/mnist_model.safetensors"
  scale_location: 0
  num_scaled_layers: 1

autoencoder:
  ae_dim: 1_024
  hidden_config: [3_136]
  ae_nonlinearity: "leakyrelu"
  batchnorm: False
  exp_param: False
  lambda_reconstruction: 1
  lambda_prediction: 0
  lambda_id: 0

batch_size: 16_384
seed: 21
save_name: "mnist_model"
save_dir: "/home/nsa325/work/koopmann/model_saves/scaling/"
print_freq: 5
