verbose: True
seed: 22
print_freq: 20
save_name: "erase"

train_data:
  dataset_name: "ImagenetteDataset"
  split: "train"
  num_samples: -1


host_model: 
  hf_name: "facebook/dinov3-vits16-pretrain-lvd1689m"
  token_idx: 0
  layer_start: 11
  layer_end: 12
  use_processor: True

optim:
  num_epochs: 1_000
  learning_rate: 1e-3
  weight_decay: 1e-4
  batch_size: 1_024
  type: "adam"
  scheduler: null

wandb:
    use_wandb: False

autoencoder:
  k_steps: 1
  in_features: 384
  hidden_config: [400, 500, 768]
  latent_features: 768
  koopman_param: "vanilla"
  bias: True
  batchnorm: True
  nonlinearity: "leaky_relu"
  lambda_reconstruction: 1e-1
  lambda_state_pred: 1e-1
  lambda_obs_pred: 1e-1